version: '3'
services:

  postgres:
    image: mdillon/postgis
    restart: on-failure
    container_name: postgresql.bike-sharing.local
    environment:
      POSTGRES_DB: bike
      POSTGRES_USER: master
      POSTGRES_PASSWORD: master
    ports:
      - 5432:5432
    networks:
      - node-red-net

  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - node-red-data:/data
    depends_on:
      - postgres

volumes:
  node-red-data:

networks:
  node-red-net:
