const logger = require('./logger');

module.exports.throwError = (statusCode, errorCode, message) => {
  logger.debug({ statusCode, errorCode, message }, 'Error');
  const error = new Error(message);
  error.statusCode = statusCode;
  error.errorCode = errorCode;
  throw error;
};

module.exports.errors = {
  STORE_NOT_FOUND: 'STORE_NOT_FOUND',
  STAND_NOT_FOUND: 'STAND_NOT_FOUND',
  STORE_TYPE_NOT_FOUND: 'STORE_TYPE_NOT_FOUND',
  SHELF_TYPE_ID_NOT_MATCH: 'SHELF_TYPE_ID_NOT_MATCH',
  SHELF_NOT_FOUND: 'SHELF_NOT_FOUND',
  SHELF_TYPE_NOT_FOUND: 'SHELF_TYPE_NOT_FOUND',
  ZONE_NOT_FOUND: 'ZONE_NOT_FOUND',
  ZONE_TYPE_NOT_FOUND: 'ZONE_TYPE_NOT_FOUND',
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  ITEM_TYPE_NOT_FOUND: 'ITEM_TYPE_NOT_FOUND',
  ITEM_ID_NOT_MATCH: 'ITEM_ID_NOT_MATCH',
  ITEM_CATEGORY_NOT_FOUND: 'ITEM_CATEGORY_NOT_FOUND',
  SHELF_CONDITION_NOT_FOUND: 'SHELF_CONDITION_NOT_FOUND',
  STAND_CONDITION_NOT_FOUND: 'STAND_CONDITION_NOT_FOUND',
  ZONE_CONDITION_NOT_FOUND: 'ZONE_CONDITION_NOT_FOUND',
  STORE_CONDITION_NOT_FOUND: 'STORE_CONDITION_NOT_FOUND',
  CONTRACTOR_NOT_FOUND: 'CONTRACTOR_NOT_FOUND',
  ACCEPTANCE_NOT_FOUND: 'ACCEPTANCE_NOT_FOUND',
  ACCEPTANCE_ID_NOT_MATCH: 'ACCEPTANCE_ID_NOT_MATCH',
  ACCEPTANCE_INCOMPLETE: 'ACCEPTANCE_INCOMPLETE',
  ACCEPTANCE_NO_STATUS_DOWNGRADE: 'ACCEPTANCE_NO_STATUS_DOWNGRADE',
  ACCEPTANCE_COMPLETED: 'ACCEPTANCE_COMPLETED',
  ACCEPTANCE_HEAD_CREATE_FAILED: 'ACCEPTANCE_HEAD_CREATE_FAILED',
  ACCEPTANCE_LINES_CREATE_FAILED: 'ACCEPTANCE_LINES_CREATE_FAILED',
  ACCEPTANCE_HEAD_UPDATE_FAILED: 'ACCEPTANCE_HEAD_UPDATE_FAILED',
  ACCEPTANCE_LINES_UPDATE_FAILED: 'ACCEPTANCE_LINES_UPDATE_FAILED',
  DISPENSE_NOT_FOUND: 'DISPENSE_NOT_FOUND',
  DISPENSE_ID_NOT_MATCH: 'DISPENSE_ID_NOT_MATCH',
  DISPENSE_INCOMPLETE: 'DISPENSE_INCOMPLETE',
  DISPENSE_NO_STATUS_DOWNGRADE: 'DISPENSE_NO_STATUS_DOWNGRADE',
  DISPENSE_COMPLETED: 'DISPENSE_COMPLETED',
  DISPENSE_HEAD_CREATE_FAILED: 'DISPENSE_HEAD_CREATE_FAILED',
  DISPENSE_LINES_CREATE_FAILED: 'DISPENSE_LINES_CREATE_FAILED',
  DISPENSE_HEAD_UPDATE_FAILED: 'DISPENSE_HEAD_UPDATE_FAILED',
  DISPENSE_LINES_UPDATE_FAILED: 'DISPENSE_LINES_UPDATE_FAILED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_STORE_NOT_FOUND: 'USER_STORE_NOT_FOUND',
  PACKAGE_TYPE_NOT_FOUND: 'PACKAGE_TYPE_NOT_FOUND',
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  PERMISSION_NOT_FOUND: 'PERMISSION_NOT_FOUND',
  ROLE_PERMISSION_NOT_FOUND: 'ROLE_PERMISSION_NOT_FOUND',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_POSITION_NOT_FOUND: 'ROLE_POSITION_NOT_FOUND',
  LOADER_NOT_FOUND: 'LOADER_NOT_FOUND',
  CONDITION_NOT_FOUND: 'CONDITION_NOT_FOUND',
  TASK_COMPLETED: 'TASK_COMPLETED',
  TASK_COMPLETE_FAILED: 'TASK_COMPLETE_FAILED',
};
